#!/system/bin/sh
#  by daniel_hk

LOG_TAG="PC_DEFAULT"
# MALI_VPLL=/sys/module/mali/parameters/mali_use_vpll
PC_DATA_PATH=/sdcard/.PerformanceControl

logi ()
{
  /system/bin/log -t $LOG_TAG -p i ": $@"
}

loge ()
{
  /system/bin/log -t $LOG_TAG -p e ": $@"
}

failed ()
{
  loge "$1: exit code $2"
  exit $2
}

# vpll on/off
#VPLL_VAL=1
#echo $VPLL_VAL > $MALI_VPLL

# Call init.defaults.sh
$PC_DATA_PATH/init.defaults.sh

case $? in
  0) logi "Set PerformanceControl defaults....done";;
  *) failed "error" $?;
     exit $?;;
esac

exit 0
